services:
  - type: web
    name: redready-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python RedReady/manage.py collectstatic --noinput && python RedReady/manage.py migrate && python RedReady/manage.py bootstrap_admin
    startCommand: gunicorn config.wsgi:application --chdir RedReady
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_FIRST_NAME
        sync: false
      - key: ADMIN_LAST_NAME
        sync: false
