# Generated by Django 6.0.2 on 2026-03-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_checked',
        ),
    ]
