# Generated by Django 6.0.2 on 2026-03-18 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulances', '0001_initial'),
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='ambulanceCode',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='ambulance',
            name='center',
        ),
        migrations.CreateModel(
            name='AmbulanceItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.IntegerField(default=1)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='ambulances.ambulance')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item')),
            ],
        ),
    ]
