# Generated by Django 6.0.2 on 2026-03-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
